baseURL: "https://ErtebateWeb.github.io/Blog/"
languageCode: 'fa'
defaultContentLanguage: 'fa'
title: 'ارتباط وب'
theme: "PaperMod"
pagination:
  pagerSize: 10

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

publishDir: "public"

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: ExampleSite
  description: "ExampleSite description"
  keywords: [Blog, Portfolio, PaperMod]
  author: Me
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "خانه"
    icon: /apple-touch-icon.png
    iconHeight: 35

  profileMode:
    enabled: false
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  homeInfoParams:
    Title: سلام مهران میرزایی هستم
    Content: >
        سلام اینجا قدری درباره همه چیز می‌نویسم

  social:
    github: "https://github.com/ErtebateWeb"
    twitter: "https://twitter.com/mmo1983"
    stackoverflow: "https://stackoverflow.com/"

  analytics:
    google:
      GA4: "G-XXXXXXX" # جایگزین UA قدیمی
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true

  editPost:
    URL: "https://github.com/<path_to_repo>/content"
    Text: "Suggest Changes"
    appendFilePath: true

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false

permalinks:
  posts: "/:year/:month/:contentbasename/"    

menu:
  main:
    - identifier: FATags
      name: تگ‌ها
      url: /fatags/
      weight: 20
    - identifier: archives
      name: آرشیو
      url: /archives/
      weight: 30

languages:
  fa:
    languageName: "farsi"
    weight: 1
    languagedirection: rtl
    taxonomies:
      category: categories
      tag: fatags
      series: series
